// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enhvhplcgqwuagjdftwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaHZocGxjZ3F3dWFnamRmdHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTYwOTksImV4cCI6MjA3Mzg5MjA5OX0.NgP6Gb_pVtVTPM6tUENL5IMstSEHA82T8II9m4-XLDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});